### ISSUE TITLE
Checkbox Display Error

### ISSUE THREAD

**Issue by blamm01** [oxendy/ReactTodo#2]
Issue: Checkbox Display Error
Fix:
```css
.container {
  max-width: 800px;
  margin: 0 auto;
  padding: 20px;
  background-color: #fff;
  border-radius: 4px;
  box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
}

h1 {
  text-align: center;
  font-size: 2.5em;
  margin-bottom: 20px;
}

form {
  display: flex;
  justify-content: center;
  margin-bottom: 20px;
  border-radius: 4px;
  border: none;
  flex-grow: 1;

}

input[type="text"] {
  padding: 10px;
  font-size: 1.2em;
  background-color: #fff;
  border-radius: 4px;
  flex-grow: 1;
}

button[type="submit"] {
  align-self: center;
  background-color: #fff;
  background-image: none;
  background-position: 0 90%;
  background-repeat: repeat no-repeat;
  background-size: 4px 3px;
  border-radius: 15px 225px 255px 15px 15px 255px 225px 15px;
  border-style: solid;
  border-width: 2px;
  box-shadow: rgba(0, 0, 0, .2) 15px 28px 25px -18px;
  box-sizing: border-box;
  color: #41403e;
  cursor: pointer;
  display: inline-block;
  font-family: Neucha, sans-serif;
  font-size: 1rem;
  line-height: 23px;
  outline: none;
  padding: .75rem;
  text-decoration: none;
  transition: all 235ms ease-in-out;
  border-bottom-left-radius: 15px 255px;
  border-bottom-right-radius: 225px 15px;
  border-top-left-radius: 255px 15px;
  border-top-right-radius: 15px 225px;
  user-select: none;
  -webkit-user-select: none;
  touch-action: manipulation;
}

ul {
  list-style: none;
  margin: 0;
  padding: 0;

}

li {
  padding: 10px;
  font-size: 1.2em;
  border-radius: 4px;
  border: solid 1px #ddd;
  margin-bottom: 10px;
  display: flex;
  align-items: center;
}

li:hover {
  background-color: #f5f5f5;
}

li:last-child {
  margin-bottom: 0;
}

.task-wrapper {
  display: flex;
  align-items: center;
  justify-content: space-between;
  width: 100%;
}

.task-wrapper span {
  flex-grow: 1;
}

.task-wrapper button {
  align-self: center;
  background-color: #fff;
  background-image: none;
  background-position: 0 90%;
  background-repeat: repeat no-repeat;
  background-size: 4px 3px;
  border-radius: 15px 225px 255px 15px 15px 255px 225px 15px;
  border-width: 2px;
  box-shadow: rgba(0, 0, 0, .2) 15px 28px 25px -18px;
  box-sizing: border-box;
  color: #41403e;
  cursor: pointer;
  display: inline-block;
  font-family: Neucha, sans-serif;
  font-size: 2rem;
  line-height: 23px;
  outline: none;
  padding: .75rem;
  text-decoration: none;
  transition: all 235ms ease-in-out;
  border-bottom-left-radius: 15px 255px;
  border-bottom-right-radius: 225px 15px;
  border-top-left-radius: 255px 15px;
  border-top-right-radius: 15px 225px;
  user-select: none;
  -webkit-user-select: none;
  touch-action: manipulation;
}




button:active {
  box-shadow: rgba(0, 0, 0, .3) 2px 8px 8px -5px;
  transform: translate3d(0, 2px, 0);
  transition:0s;
}

.done {
  text-decoration: line-through;
  color: #ccc;
}
 .done .task-wrapper {
  opacity: 0.5;
}

.done .label-text {
  text-decoration: line-through;
  color: #ccc;
}

.disabled {
  opacity: 0.5;
  text-decoration: line-through;
  color: #ccc;
}

.disabled .label-text {
  text-decoration: line-through;
  color: #ccc;
}

.diabled .checkmark{
  color: #ccc;
  cursor: block;
}

button:hover {
  box-shadow: rgba(0, 0, 0, .3) 2px 8px 4px -6px;
}
/*
.checkbox{
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  font-size: 3rem;
  font-weight: 4rem;
  border-radius: 15px 225px 255px 15px 15px 255px 225px 15px;
  background-color: #fff;
  color: rgb(252, 1, 1);
  box-shadow: rgba(0, 0, 0, .2) 15px 28px 25px -18px;
  border: 4px;
  cursor: pointer;
  transition: all 235ms 0.5s ease-in-out;
  transform: all 0.5s ease;
  letter-spacing: 0.1rem;
  font-weight: 600;
  font-size: 1rem;
}
.checkbox:before{
  margin: 0;
  box-sizing: border-box;
  border-radius: 15px 225px 255px 15px 15px 255px 225px 15px;
  box-shadow: rgba(0, 0, 0, .2) 15px 28px 25px -18px;
  border-style: solid;
  border-bottom-left-radius: 15px 255px;
  border-bottom-right-radius: 225px 15px;
  border-top-left-radius: 255px 15px;
  border-top-right-radius: 15px 225px;
}
.checkbox:after{
  margin: 0;
  padding: 0;
  box-sizing: border-box;
  border-radius: 15px 225px 225px 15px 30px;
  box-shadow: rgba(0, 0, 0, 0.3) 15px 30px 15px 225px;
  border-style: solid;
  border-bottom-left-radius: 15px 255px;
  border-bottom-right-radius: 225px 15px;
  border-top-left-radius: 255px 15px;
  border-top-right-radius: 15px 225px;
}
.checkbox:hover{
  color: #fff;
  font-size: 1rem;
  font-weight: 300;
  letter-spacing: 0.3rem;
  text-shadow: 0 0 10px #41403e,
               0 0 20px #41403e,
               0 0 40px #41403e,
               0 0 80px #41403e,
               0 0 120px #41403e;
}

*/
/* Customize the label (the container) */
.text-wrapper {
  display: block;
  position: relative;
  padding-left: 35px;
  margin-bottom: 12px;
  cursor: pointer;
  font-size: 22px;
  -webkit-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
}

/* Hide the browser's default checkbox */
.text-wrapper input {
  position: absolute;
  opacity: 0;
  cursor: pointer;
  height: 0;
  width: 0;
}

/* Create a custom checkbox */
.checkmark {
  margin: 0;
  padding: 0;
  align-self: center;
  display: inline;
  box-sizing: border-box;
  font-size: 3rem;
  font-weight: 4rem;
  background-color: #fff;
  color: gray;
  box-shadow: rgba(0, 0, 0, .2) 15px 28px 25px -18px;
  cursor: pointer;
  
}

/* On mouse-over, add a grey background color */
.text-wrapper:hover input ~ .checkmark {
  background-color: #ccc;
}

/* When the checkbox is checked, add a blue background */
.text-wrapper input:checked ~ .checkmark {
  background-color: #f38721;
}

/* Create the checkmark/indicator (hidden when not checked) */
.checkmark:after {
  content: "";
  position: absolute;
  display: none;
}

/* Show the checkmark when checked */
.text-wrapper input:checked ~ .checkmark:after {
  display: block;
}

/* Style the checkmark/indicator */
.text-wrapper .checkmark:after {
  left: 9px;
  top: 5px;
  width: 5px;
  height: 10px;
  border: solid white;
  border-width: 0 3px 3px 0;
  -webkit-transform: rotate(45deg);
  -ms-transform: rotate(45deg);
  transform: rotate(45deg);
}

.taskName {
  font-size: 20px;
}
```
